"use client"
import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import Provider from '@/Provider/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const queryClient = new QueryClient()


export default function RootLayout({ children }) {

  return (


    <html lang="en">

      <Provider>
        <body className={`max-w-screen-xl mx-auto ${inter.className}`}>
          <Navbar></Navbar>
          <div className='min-h-screen '>
            {children}
          </div>
          <Footer></Footer>
        </body>
      </Provider>

    </html>


  )
}
